spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0

