server:
  port: 8080
spring:
  application:
    name: oauth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        ###连接池最大连接数(用负值表示没有限制)
        max-active: 8
        ###连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0
    ###连接超时时间
    timeout: 10000
  mvc:
    ignore-default-model-on-redirect: false
    locale: zh_CN
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    root: info
